# Generated by Django 4.0.2 on 2022-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=1000)),
                ('signin', models.DateField(auto_now_add=True)),
                ('signout', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
