# Generated by Django 4.0.2 on 2022-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='signedin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signin',
            name='signout',
            field=models.DateField(),
        ),
    ]
