# Generated by Django 4.0.2 on 2022-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_signin_signout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='signin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='signout',
            field=models.DateTimeField(null=True),
        ),
    ]
